### PR TITLE
fix select userbyid result fix #22

### LINKED ISSUE #22: Row count check crashed database

### PR DESCRIPTION
**Pull request by mhmdshorafa**

### CODE REVIEW

File: src/backEnd/controllers/usersControllers.js [hunk 1]
```diff
@@ -37,6 +37,7 @@ module.exports = {
     if(req.signedCookies['userID']){
       const userId = req.signedCookies['userID'];
       usersdb.selectUserById(userId, (err, user) => {
+        console.log('err',err);
```
Comment (ronanyeah) [inline src/backEnd/controllers/usersControllers.js]: @mhmdshorafa please remove
